import Cart from "@/components/Cart";
import ContactForm from "@/components/checkout/ContactForm";
import ContactInfo from "@/components/checkout/ContactInfo";
import ProductList from "@/components/checkout/ProductList";
import Regions from "@/components/checkout/Regions";
import MobileNav from "@/components/MobileNav";
import { useShop } from "@/context/context";
import { Montserrat } from "next/font/google";
import Head from "next/head";

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

const Checkout = () => {
  const { cartOpen, sideNav } = useShop();
  return (
    <>
      <Head>
        <title>Checkout</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={`${montserrat.className}`}>
        {cartOpen && <Cart />}
        {sideNav && <MobileNav />}
        <section className="bg-white">
          <div className="px-5 py-12 mx-auto md:px-12 lg:px-16 max-w-7xl">
            <div className="lg:grid grid-cols-2 gap-4">
              <div className="lg:order-2">
                <h1 className="text-xl">Your Order</h1>
                <div className="mt-4">
                  <ProductList />
                </div>
              </div>
              <div className="lg:order-1">
                <ContactInfo />
                <ContactForm />
                <Regions />
              </div>
            </div>
          </div>
        </section>
      </div>
    </>
  );
};

export default Checkout;
