import Cart from "@/components/Cart";
import MobileNav from "@/components/MobileNav";
import SearchComponent from "@/components/Search";
import { useShop } from "@/context/context";
import { AnimatePresence } from "framer-motion";
import { Montserrat } from "next/font/google";
import Head from "next/head";

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

const Contact = () => {
  const { cartOpen, sideNav, searchOpen } = useShop();
  return (
    <>
      <Head>
        <title>Contact</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AnimatePresence>
        {cartOpen && <Cart />}
        {sideNav && <MobileNav />}
        {searchOpen && <SearchComponent />}
      </AnimatePresence>
      <div
        className={`${montserrat.className} px-5 py-12 mx-auto md:px-12 lg:px-16 max-w-7xl`}
      >
        <h1 className="text-center text-5xl text-[#123026]">
          WE WOULD LOVE TO HEAR FROM YOU
        </h1>
        <h3 className="text-[#123026] my-8">
          QUESTIONS OR ENGRAVING INSTRUCTIONS:
        </h3>
        <div>
          <h1 className="font-semibold text-[#123026]">CALL US</h1>
          <h3 className="text-[#123026]">(+254) 712-344567</h3>
        </div>
        <div className="mt-6">
          <h1 className="font-semibold text-[#123026]">EMAIL</h1>
          <h3 className="text-[#123026]">Goodlite - goodlite@gmail.com</h3>
        </div>
        <div>
          <form className="mt-6">
            <h1 className="font-semibold text-[#123026]">
              OR USE THE FORM BELOW TO CONTACT US
            </h1>
            <div className="relative mt-6">
              <input
                type="text"
                className="border-2 w-full p-4 input-focus"
                placeholder=" "
              />
              <label className="absolute top-2 left-2 p-2 text-base text-gray-500 pointer-events-none bg-white transition-all duration-200 ease-out">
                Name *
              </label>
            </div>
            <div className="relative mt-6">
              <input
                type="text"
                className="border-2 w-full p-4 input-focus"
                placeholder=" "
              />
              <label className="absolute top-2 left-2 p-2 text-base text-gray-500 pointer-events-none bg-white transition-all duration-200 ease-out">
                Email *
              </label>
            </div>
            <div className="relative mt-6">
              <input
                type="text"
                className="border-2 w-full p-4 input-focus"
                placeholder=" "
              />
              <label className="absolute top-2 left-2 p-2 text-base text-gray-500 pointer-events-none bg-white transition-all duration-200 ease-out">
                Phone *
              </label>
            </div>
            <div className="relative mt-6">
              <textarea
                className="border-2 w-full p-4 input-focus"
                placeholder=" "
              />
              <label className="absolute top-2 left-2 p-2 text-base text-gray-500 pointer-events-none bg-white transition-all duration-200 ease-out">
                Message *
              </label>
            </div>
            <button
              className="p-4 text-white bg-[#123026] mt-6 hover:bg-[#1e4f3f] transition duration-300 ease-in-out"
              type="submit"
            >
              Contact Us
            </button>
          </form>
        </div>
      </div>
    </>
  );
};

export default Contact;
