import Cart from "@/components/Cart";
import MobileNav from "@/components/MobileNav";
import SearchComponent from "@/components/Search";
import { useShop } from "@/context/context";
import { AnimatePresence } from "framer-motion";
import { Montserrat } from "next/font/google";
import Head from "next/head";

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

const Refund = () => {
  const { cartOpen, sideNav, searchOpen } = useShop();
  return (
    <>
      <Head>
        <title>Refund Policy</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AnimatePresence>
        {cartOpen && <Cart />}
        {sideNav && <MobileNav />}
        {searchOpen && <SearchComponent />}
      </AnimatePresence>
      <div
        className={`${montserrat.className} px-5 py-12 mx-auto md:px-12 lg:px-16 max-w-7xl text-[#123026]`}
      >
        <h1 className="text-center text-5xl">Return & Refund Policy</h1>
        <h3 className="my-8">
          Goodlite offers a 5-day refund policy for all products. If you are not
          completely satisfied with your purchase, you may return the product to
          us within 5 days of the purchase date for a full refund. To be
          eligible for a refund, the product must be in its original condition
          and packaging. Please note that shipping costs are non-refundable.
        </h3>
        <h3 className="my-8">
          To initiate a refund, please contact us at{" "}
          <span className="text-black italic cursor-pointer border-a-expand">
            goodlite@gmail.com
          </span>{" "}
          with your order number and reason for the return. Once we receive your
          request, we will provide you with a return authorization number and
          instructions on how to return the product. Please note that we are not
          responsible for any shipping costs associated with the return of the
          product.
        </h3>
        <h3 className="my-8">
          Once we receive the returned product, we will inspect it to ensure
          that it is in its original condition and packaging. If the product
          meets our refund policy criteria, we will issue a refund to your
          original method of payment. Please note that it may take several
          business days for the refund to appear on your account.
        </h3>
        <div>
          <h2 className="text-xl font-semibold">Defective or Damaged Goods:</h2>
          <h3 className="my-8">
            If you receive a defective or damaged product, please contact us at{" "}
            <span className="text-black italic cursor-pointer border-a-expand">
              goodlite@gmail.com{" "}
            </span>
            within 7 days of receiving the product. We will work with you to
            resolve the issue as quickly as possible, which may include a
            refund, exchange, or replacement of the product.
          </h3>
          <p>
            Thank you for choosing Goodlite. If you have any questions or
            concerns about our refund policy, please do not hesitate to contact
            us.
          </p>
        </div>
      </div>
    </>
  );
};

export default Refund;
